name: Frontend workshop demo
on:
  push:
    branches: 
        - 'feature/**'
        - 'bugfix/**'
jobs:
    lint-jobs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v3
              with:
                node-version: '24.x'
                cache: 'npm'
            - run: node -v
            - run: npm ci
            - run: npm run lint
