name: Frontend workshop demo
on:
  push:
    branches: 
        - 'feature/**'
        - 'bugfix/**'
jobs:
   build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v6
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: '18'
                cache: 'npm'
              name: Install dependencies and build
            - run: node -v
            - run: npm ci
            - run: npm run build